# Generated by Django 5.0.3 on 2024-03-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='MainUserEmail',
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
