# Generated by Django 5.0.3 on 2024-03-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='MainUserEmail',
        ),
    ]
