# Generated by Django 5.0.3 on 2024-04-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
    ]
