# Generated by Django 5.0.3 on 2024-04-11 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20240411_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movementadd',
            options={'verbose_name': 'Movement'},
        ),
        migrations.AddField(
            model_name='movementadd',
            name='rest_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Rest Time (seconds)'),
        ),
        migrations.AlterField(
            model_name='movementadd',
            name='repetitions',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
