# Generated by Django 5.0.3 on 2024-03-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_mainuser_firstname_remove_mainuser_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExersiseAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_name', models.CharField(max_length=225)),
                ('movement_pic', models.URLField()),
                ('body_part', models.CharField(choices=[('foot', 'Foot'), ('chest', 'Chest'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('shoulders', 'Shoulders'), ('back', 'Back'), ('abs', 'Abs and Core'), ('glutes', 'Glutes')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ExersiseName',
        ),
    ]
