# Generated by Django 5.0.3 on 2024-03-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_mainuser_firstname_remove_mainuser_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'cm'), ('in', 'in')], default='cm', max_length=2),
        ),
    ]
