# Generated by Django 5.0.3 on 2024-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_mainuser_height_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=2),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_specific', 'Not Specific')], default='not_specific', max_length=20),
        ),
    ]
