# Generated by Django 5.0.3 on 2024-03-22 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_mainuser_weight_unit_alter_mainuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='UserHeight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='UserWeight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
