# Generated by Django 5.0.3 on 2024-04-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_delete_normaluser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='mainuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='username',
        ),
    ]
