# Generated by Django 5.0.3 on 2024-04-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_mainuser_email_mainuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
