# Generated by Django 5.0.3 on 2024-04-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_mainuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweight',
            name='weight_unit',
            field=models.CharField(choices=[(0, 'Kilogram'), (1, 'Pound')], default='kg', max_length=2),
        ),
    ]
